# Generated by Django 3.1.5 on 2021-01-25 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertybook',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
